apiVersion: v1
kind: ServiceAccount
metadata:
  name: reverse-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reverse-proxy-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reverse-proxy-binding
subjects:
  - kind: ServiceAccount
    name: reverse-proxy
    namespace: default
roleRef:
  kind: ClusterRole
  name: reverse-proxy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      serviceAccountName: reverse-proxy
      containers:
      - name: reverse-proxy
        image: dhirajbomma/homelab-utils-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8008
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  selector:
    app: reverse-proxy
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008

